### ISSUE TITLE
need hep with the telemetry

### ISSUE THREAD

**Issue by justinross7j** [mike-koch/ets2-telemetry-server#2]
im trying to use it on ats. my server says ats is running and my tablet says its connected but it doesn't show any display on it like mph or rpm or anything. got any tips on how i can fix this? thanks

**Comment by nak0604** [comment]
I have the same issue here

**Comment by mike-koch** [comment]
@nak0604 Do you get this message when launching ATS?

![Screenshot](https://lh5.googleusercontent.com/-sPPa9QvEtow/UsUkK7CsIsI/AAAAAAAAAKE/LX0Rf2N7UyY/w501-h447-no/telemetry.png)

**Comment by nak0604** [comment]
@mike-koch Ah, I restarted ATS after double checking the installation of the plugin and its running smoothly now xP Thank you very much for the conversion! Hope for more updates :)

**Comment by mike-koch** [comment]
Awesome. Always make sure after you restart ATS after installing the plugin! (since plugins are loaded only at launch)
